# Generated by Django 5.2.5 on 2025-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('apellido_proveedor', models.CharField(max_length=50)),
                ('telefono_proveedor', models.CharField(max_length=15)),
                ('correo_proveedor', models.CharField(max_length=255)),
                ('estado_proveedor', models.CharField(max_length=20)),
            ],
        ),
    ]
