# Generated by Django 5.2.5 on 2025-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('clienteNom', models.CharField(max_length=50)),
                ('clienteApel', models.CharField(max_length=50)),
                ('clienteTel', models.CharField(max_length=10)),
                ('clienteCor', models.CharField(max_length=100)),
                ('clienteEst', models.CharField(max_length=20)),
            ],
        ),
    ]
